language: android
dist: trusty
jdk: oraclejdk11
sudo: false

android:
components:
    - tools
    - platform-tools
    - build-tools-33.0.0
    - android-32
    - extra-android-m2repository
before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  # Hack to accept Android licenses
  - yes | sdkmanager "platforms;android-32"

script:
  - ./gradlew assembleRelease
